version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: memoir_db
      POSTGRES_USER: memoir_user
      POSTGRES_PASSWORD: memoir_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
