name: Run Api Tests
run-name: ${{ github.actor }} is testing out ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - name: Checkout to api folder
        run: cd apps/api/
      - name: Install docker
        run: docker --version
      - name: Install drizzle kit
        run: bun add -D drizzle-kit
      - name: Install npm dependencies
        run: bun i
