name: Run Api Tests
run-name: ${{ github.actor }} is testing out ${{ github.event.pull_request.title }}

on: [pull_request]

jobs:
  test:
    branches: [main]
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - name: Install docker
        run: docker --version
