name: Client Formatting and Linting
run-name: Run Linter and Formatter on ${{ github.event.pull_request.title }} by ${{ github.event.sender.login }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/api
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Format
        run: bun run format
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: format code
  linting:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/api
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
