name: Run Client Tests
run-name: ${{ github.actor }} is testing out ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "v2.24.1" # the full version of `docker-compose` command
      - name: Install npm dependencies
        run: bun i
      - name: checkout to client package
        run: cd apps/client
      - name: install playwright browsers
        run: bunx playwright install --with-deps
      - name: Create .env file
        run: |
          touch .env
          echo NEXT_PUBLIC_SITE=http://localhost:3000 >> .env
          echo API_URL=http://localhost:3001 >> .env
      - name: Run tests
        run: bun run test
