name: Run Client Tests
run-name: ${{ github.actor }} is testing out ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - main
    paths:
      - "./apps/client/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "v2.24.1" # the full version of `docker-compose` command
      - name: Install npm dependencies
        run: bun i
      - name: install playwright browsers
        working-directory: ./apps/client
        run: bunx playwright install --with-deps
      - name: Create .env file
        working-directory: ./apps/client
        run: |
          touch .env
          echo NEXT_PUBLIC_SITE=http://localhost:3000 >> .env
          echo API_URL=http://localhost:3001 >> .env
      - name: Run tests
        working-directory: ./apps/client
        run: bun run test
