name: Client Formatting and Linting
run-name: Run Linter and Formatter on ${{ github.event.pull_request.title }} by ${{ github.event.sender.login }}

on:
  pull_request:
    branches:
      - main
    paths:
      - "./apps/client/**"
    paths-ignore:
      - "./apps/api/**"

jobs:
  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/api
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Format
        run: bun run format
      - name: stage changes
      - run: git commit -m 'formatting'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linting:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/api
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
